import type { Metadata } from "next";
import "@/app/(root)/globals.css";
import { Toaster } from "@/components/ui/sonner";
import localFont from "next/font/local";

const chillax = localFont({
  src: [
    {
      path: "../../public/fonts/WEB/fonts/Chillax-Extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/WEB/fonts/Chillax-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/WEB/fonts/Chillax-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/WEB/fonts/Chillax-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/WEB/fonts/Chillax-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/WEB/fonts/Chillax-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-chillax",
});

const poppins = localFont({
  src: [
    {
      path: "../../public/fonts/OTF/Poppins-Light.ttf",
      weight: "300",
      style: "Light",
    },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Kindlewood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`font-sans ${chillax.variable} ${poppins.variable}`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
