import type { Metadata } from "next";
import DashNav from "@/components/dashNav";

export const metadata: Metadata = {
  title: "LJM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <div className="grid h-screen">
          <DashNav />
          {children}
        </div>
      </body>
    </html>
  );
}
